- name: "[{{ service.name }}] Cоздание config"
  vars:
    config_file: "{{ lookup('template', '../../{{ service.name }}/{{ config_item }}.j2') }}"
  community.docker.docker_config:
    name: "{{ config_item }}"
    labels:
      config: "{{ config_file | hash('sha1') }}"
    data: "{{ config_file | b64encode }}"
    data_is_b64: true
    state: present
