---
- name: "[{{ service.name }}] Конфигурация конфига"
  ansible.builtin.include_tasks: "../_utils_/configs/config.yml"
  loop:
    - nginx.conf
  loop_control:
    loop_var: config_item

- name: "[{{ service.name }}] Деплой сервиса"
  community.docker.docker_swarm_service:
    name: "{{ service.name }}"
    image: "nginx:{{ service.version }}"
    state: present
    publish:
      - mode: ingress
        protocol: tcp
        published_port: 80
        target_port: 80
    networks:
      - "{{ deploy_docker_network_name }}"
    configs:
      - config_name: nginx.conf
        filename: /etc/nginx/nginx.conf
  tags: "{{ service.name }}"
