---
- name: Preconfig
  hosts: cluster
  tasks:
    - name: Docker installation
      block:
        - name: Add universal repo
          apt_repository:
            repo: "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
            state: present

        - name: Install additional packages
          apt:
            name:
              - apt-transport-https
              - ca-certificates
              - curl
              - gnupg
              - lsb-release
            update-cache: yes
            cache_valid_time: 86400

        - name: Download Docker repo key
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            keyring: /usr/share/keyrings/docker-archive-keyring.gpg
            state: present

        - name: Set permissions on Docker repo key
          file:
            path: /usr/share/keyrings/docker-archive-keyring.gpg
            mode: "0644"

        - name: Add Docker repo
          apt_repository:
            repo: >
              deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
            state: present
            update-cache: yes
            filename: docker

        - name: Install Docker-ce
          apt:
            pkg:
              - docker-ce
              - docker-ce-cli
              - containerd.io
              - docker-buildx-plugin
              - docker-compose-plugin
            update-cache: yes
            cache_valid_time: 86400

        - name: Docker restarted
          service:
            name: docker
            state: restarted
            enabled: yes
      become: yes

    - name: Install Docker-compose
      block:
        - name: Get latest Docker-compose version
          uri:
            url: https://api.github.com/repos/docker/compose/releases/latest
            body_format: json
          register: page

        - name: Install Docker-compose
          get_url:
            url: "https://github.com/docker/compose/releases/download/{{ page.json.tag_name }}/docker-compose-Linux-x86_64"
            dest: /usr/local/bin/docker-compose
            mode: 0755
      become: yes

    - name: Finish installation
      block:
        - name: Add user in Docker group
          user:
            name: "{{ansible_user}}"
            groups: docker
            append: yes

        - name: Reboot
          reboot:
      become: yes
