version: "3"
services:
  api:
    image: localhost:5000/api:latest
    secrets:
    - source: api.env
      target: /opt/app/.env
    restart: always
    ports:
    - 3002:3000
    networks:
    - myNetwork
    depends_on:
    - rmq
  rmq:
    image: rabbitmq:3-management
    restart: always
    networks:
    - myNetwork
    environment:
    - RABBITMQ_DEFAULT_USER=admin
    - RABBITMQ_DEFAULT_PASS=admin

networks:
  myNetwork:
    driver: overlay

secrets:
  api.env:
    external: true