---
- name: Инициализация Swarm кластера
  community.docker.docker_swarm:
    state: present
    advertise_addr: "{{ swarm_cluster_addr }}"
  register: join_tokens_info

- name: Сохранение join-token
  ansible.builtin.set_fact:
    join_token_manager: "{{ join_tokens_info.swarm_facts.JoinTokens.Manager }}"
    join_token_worker: "{{ join_tokens_info.swarm_facts.JoinTokens.Worker }}"
    cacheable: true
