- name: "[{{ service.name }}] Конфигурация секретов"
  block:
    - name: "[{{ service.name }}] Попытка создания секрета"
      include_tasks: "./secret-create.yml"

  rescue:
    - name: "[{{ service.name }}] Удаление сервиса для обновления секрета"
      community.docker.docker_swarm_service:
        name: "{{ service.name }}"
        state: absent
    - name: "[{{ service.name }}] Обновление секрета"
      include_tasks: "./secret-create.yml"
