- name: "[{{ service.name }}] Cоздание секрета"
  vars:
    envFile: "{{ lookup('template', '../../{{ service.name }}/.env.j2') }}"
  community.docker.docker_secret:
    name: "{{ service.name }}.env"
    labels:
      secret: "{{ envFile | hash('sha1') }}"
    data: "{{ envFile | b64encode }}"
    data_is_b64: true
    state: present
